name: "Push image"
description: "Build, scan and push image to GitHub Container Registry"

inputs:
  image_name:
    description: "Docker image name"
    required: true
  image_tag:
    description: "Docker image tag"
    required: true
  context:
    description: "Path to directory containing Dockerfile"
    required: true
  registry_password:
    description: "GITHUB_TOKEN"
    required: true
  fail_on_security_vulnerabilities:
    description: "If false allow security vulnerabilities in built image"
    default: false
    required: false
  build_args:
    description: "Docker build args"
    default: ""
    required: false

runs:
  using: "composite"
  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ inputs.registry_password }}

    - name: Build and export to Docker
      uses: docker/build-push-action@v5
      with:
        context: ${{ inputs.context }}
        platforms: linux/amd64
        load: true
        tags: ${{ inputs.image_name }}:${{ inputs.image_tag }}
        build-args: ${{ inputs.build_args }}

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: ${{ inputs.context }}
        platforms: linux/amd64
        push: ${{ github.ref == 'refs/heads/main' }}
        tags: ${{ inputs.image_name }}:${{ inputs.image_tag }}
        build-args: ${{ inputs.build_args }}

    - name: Delete local image
      shell: bash
      run: docker rmi ${{ inputs.image_name }}:${{ inputs.image_tag }} || true
