name: "Push image"
description: "Build, scan and push image to GitHub Container Registry"

inputs:
  image_name:
    description: "Docker image name"
    required: true
  image_tag:
    description: "Docker image tag"
    required: true
  context:
    description: "Path to directory containing Dockerfile"
    required: true
  registry_password:
    description: "GITHUB_TOKEN"
    required: true

runs:
  using: "composite"
  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ inputs.registry_password }}

    - name: Build and export to Docker
      uses: docker/build-push-action@v2
      with:
        context: ${{ inputs.context }}
        platforms: linux/amd64
        load: true
        tags: ${{ inputs.image_name }}:${{ inputs.image_tag }}

    - name: Run Lacework vulnerability scanner
      if: inputs.context != './elixir-cypress-ci'
      run: |
        curl -L https://github.com/lacework/lacework-vulnerability-scanner/releases/latest/download/lw-scanner-linux-amd64 -o lw-scanner
        chmod +x lw-scanner
        ./lw-scanner image evaluate ${{ inputs.image_name }} ${{ inputs.image_tag }} --build-id ${{ github.run_id }}
      env:
        LW_ACCESS_TOKEN: ${{ secrets.LW_ACCESS_TOKEN }}
        LW_ACCOUNT_NAME: ${{ secrets.LW_ACCOUNT_NAME }}
        LW_ACCOUNT_SUFFIX: ${{ secrets.LW_ACCOUNT_SUFFIX }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: ${{ inputs.context }}
        platforms: linux/amd64
        push: ${{ github.ref == 'refs/heads/main' }}
        tags: ${{ inputs.image_name }}:${{ inputs.image_tag }}
