name: elixir-cypress-ci

on:
  push:
    branches:
      - 'main'
    paths:
      - 'elixir-cypress-ci/**'
  workflow_dispatch:
  pull_request:
    types: [assigned, opened, synchronize, reopened]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build and push image
        uses: ./.github/actions/push-image
        with:
          image_name: ghcr.io/multiverse-io/elixir-cypress-ci
          image_tag: 1.14.5-erlang-26.1.2-debian-bookworm-20231009-slim
          context: ./elixir-cypress-ci
          registry_password: ${{ secrets.GITHUB_TOKEN }}
          fail_on_security_vulnerabilities: false
          lacework_access_token: ${{ secrets.LW_ACCESS_TOKEN }}
