name: elixir-ci

on:
  push:
    branches:
      - "main"
  workflow_dispatch:
  pull_request:
    types: [assigned, opened, synchronize, reopened]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build and push Alpine image otp 26 elixir 1.15
        uses: ./.github/actions/push-image
        with:
          image_name: ghcr.io/multiverse-io/elixir-ci
          image_tag: 1.15.8-erlang-26.2.5-alpine-3.20.1
          context: ./elixir-ci/alpine
          registry_password: ${{ secrets.GITHUB_TOKEN }}
          lacework_access_token: ${{ secrets.LW_ACCESS_TOKEN }}
          build_args: |
            ELIXIR_VERSION=1.15.8
            ERLANG_VERSION=26.2.5
            ALPINE_VERSION=3.20.1

      - name: Build and push Debian image otp 26 elixir 1.17
        uses: ./.github/actions/push-image
        with:
          image_name: ghcr.io/multiverse-io/elixir-ci
          image_tag: 1.17.2-erlang-26.2.5.1-debian-bookworm-20240701-slim
          context: ./elixir-ci/debian
          registry_password: ${{ secrets.GITHUB_TOKEN }}
          lacework_access_token: ${{ secrets.LW_ACCESS_TOKEN }}
          build_args: |
            ELIXIR_VERSION=1.17.2
            ERLANG_VERSION=26.2.5.1
            DEBIAN_VERSION=bookworm-20240701-slim

      - name: Build and push Debian image otp 26 elixir 1.18
        uses: ./.github/actions/push-image
        with:
          image_name: ghcr.io/multiverse-io/elixir-ci
          image_tag: 1.18.1-erlang-26.2.5.6-debian-bookworm-20241223-slim
          context: ./elixir-ci/debian
          registry_password: ${{ secrets.GITHUB_TOKEN }}
          lacework_access_token: ${{ secrets.LW_ACCESS_TOKEN }}
          build_args: |
            ELIXIR_VERSION=1.18.1
            ERLANG_VERSION=26.2.5.6
            DEBIAN_VERSION=bookworm-20241223-slim

      - name: Build and push Alpine image otp 26 elixir 1.14
        uses: ./.github/actions/push-image
        with:
          image_name: ghcr.io/multiverse-io/elixir-ci
          image_tag: 1.14.5-erlang-26.2.5.2-alpine-3.20.1
          context: ./elixir-ci/alpine
          registry_password: ${{ secrets.GITHUB_TOKEN }}
          lacework_access_token: ${{ secrets.LW_ACCESS_TOKEN }}
          build_args: |
            ELIXIR_VERSION=1.14.5
            ERLANG_VERSION=26.2.5.2
            ALPINE_VERSION=3.20.1

      - name: Build and push Debian image
        uses: ./.github/actions/push-image
        with:
          image_name: ghcr.io/multiverse-io/elixir-ci
          image_tag: 1.16.0-erlang-26.2.1-debian-bookworm-20231009-slim
          context: ./elixir-ci/debian
          registry_password: ${{ secrets.GITHUB_TOKEN }}
          lacework_access_token: ${{ secrets.LW_ACCESS_TOKEN }}
          build_args: |
            ELIXIR_VERSION=1.16.0
            ERLANG_VERSION=26.2.1
            DEBIAN_VERSION=bookworm-20231009-slim
