name: elixir-cypress-ci

on:
  push:
    branches:
      - 'main'
    paths:
      - 'elixir-cypress-ci/**'
  workflow_dispatch:
  pull_request:
    types: [assigned, opened, synchronize, reopened]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build and push image otp 25
        uses: ./.github/actions/push-image
        with:
          image_name: ghcr.io/multiverse-io/elixir-cypress-ci
          image_tag: 1.14.2-erlang-25.1.2-debian-bullseye-20221004-slim
          context: ./elixir-cypress-ci
          registry_password: ${{ secrets.GITHUB_TOKEN }}
          fail_on_security_vulnerabilities: false
          lacework_access_token: ${{ secrets.LW_ACCESS_TOKEN }}
          build_args: |
            ELIXIR_VERSION=1.14.2
            ERLANG_VERSION=25.1.2
            DEBIAN_VERSION=bullseye-20221004-slim

      - name: Build and push image otp 26
        uses: ./.github/actions/push-image
        with:
          image_name: ghcr.io/multiverse-io/elixir-cypress-ci
          image_tag: 1.14.5-erlang-26.1.2-debian-bookworm-20231009-slim
          context: ./elixir-cypress-ci
          registry_password: ${{ secrets.GITHUB_TOKEN }}
          fail_on_security_vulnerabilities: false
          lacework_access_token: ${{ secrets.LW_ACCESS_TOKEN }}
          build_args: |
            ELIXIR_VERSION=1.14.5
            ERLANG_VERSION=26.1.2
            DEBIAN_VERSION=bookworm-20231009-slim
