name: elixir-ci

on:
  push:
    branches:
      - 'main'
    paths:
      - 'elixir-ci/**'
  workflow_dispatch:
  pull_request:
    types: [assigned, opened, synchronize, reopened]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build and push image
        uses: ./.github/actions/push-image
        with:
          image_name: ghcr.io/multiverse-io/elixir-ci
          image_tag: 1.13.2-erlang-24.2.1-alpine-3.15.0
          context: ./elixir-ci
          registry_password: ${{ secrets.GITHUB_TOKEN }}
          lacework_access_token: ${{ secrets.LW_ACCESS_TOKEN }}
