name: elixir-ci

on:
  push:
    branches:
      - 'main'
    paths:
      - 'elixir-ci/**'
  workflow_dispatch:
  pull_request:
    types: [assigned, opened, synchronize, reopened]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build and push image
        uses: ./.github/actions/push-image
        with:
          tag: ghcr.io/multiverse-io/elixir-ci:1.12.3-erlang-24.1.2-alpine-3.14.2
          context: ./elixir-ci
          registry_password: ${{ secrets.GITHUB_TOKEN }}
