name: elixir-ci

on:
  push:
    branches:
      - 'main'
    paths:
      - 'elixir-ci/**'
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build and push image
        uses: ./.github/actions/push-image
        with:
          tag: ghcr.io/multiverse-io/elixir-ci:1.12.2-erlang-24.0.4-alpine-3.14.0
          context: ./elixir-ci
