name: elixir-ci

on:
  push:
    branches:
      - "main"
    paths:
      - "elixir-ci/**"
  workflow_dispatch:
  pull_request:
    types: [assigned, opened, synchronize, reopened]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build and push Alpine image
        uses: ./.github/actions/push-image
        with:
          image_name: ghcr.io/multiverse-io/elixir-ci
          image_tag: 1.14.2-erlang-25.1.2-alpine-3.18.0
          context: ./elixir-ci/alpine
          registry_password: ${{ secrets.GITHUB_TOKEN }}
          lacework_access_token: ${{ secrets.LW_ACCESS_TOKEN }}

      - name: Build and push Debian image
        uses: ./.github/actions/push-image
        with:
          image_name: ghcr.io/multiverse-io/elixir-ci
          image_tag: 1.15.6-erlang-26.1.1-debian-bookworm-20230612-slim
          context: ./elixir-ci/debian
          registry_password: ${{ secrets.GITHUB_TOKEN }}
          lacework_access_token: ${{ secrets.LW_ACCESS_TOKEN }}
